name: resterland/rlt3sitepackage
label: 'Resterland TYPO3 Sitepackage'
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - rlt3sitepackage/custom-properties
optionalDependencies:
  - typo3/felogin
  - apache-solr-for-typo3/solr
  - typo3/form
  - typo3/seo-sitemap
