### Site-specific settings
#
# Usage in TypoScript and Page TSconfig:
# -> e.g. {$page.identifier.navigation.mainRoot}
# Usage in Fluid (needs dataProcessing, see "Page.typoscript"):
# -> e.g. {site.configuration.settings.page.identifier.navigation.mainRoot}
categories:
  rlt3sp: ~
  rlt3sp.templates:
    parent: rlt3sp

settings:
  styles.templates.templateRootPath:
    default: ''
    type: string
    category: rlt3sp.templates
  styles.templates.partialRootPath:
    default: ''
    type: string
    category: rlt3sp.templates
  styles.templates.layoutRootPath:
    default: ''
    type: string
    category: rlt3sp.templates


