### Site-specific settings
#
# Usage in TypoScript and Page TSconfig:
# -> e.g. {$page.identifier.navigation.mainRoot}
# Usage in Fluid (needs dataProcessing, see "Page.typoscript"):
# -> e.g. {site.configuration.settings.page.identifier.navigation.mainRoot}
categories:
  rlt3sitepackage: ~
  rlt3sitepackage.templates:
    parent: rlt3sitepackage
  rlt3sitepackage.meta:
    parent: rlt3sitepackage
  rlt3sitepackage.config:
    parent: rlt3sitepackage

  rlt3sitepackage.theme:
    parent: rlt3sitepackage

  rlt3sitepackage.navigation:
    parent: rlt3sitepackage.theme

  rlt3sitepackage.style:
    parent: rlt3sitepackage.theme

  rlt3sitepackage.css-variables:
    parent: rlt3sitepackage.style

  rlt3sitepackage.header:
    parent: rlt3sitepackage.theme
  rlt3sitepackage.footer:
    description: 'Footer settings and configuration'
    parent: rlt3sitepackage.theme
  rlt3sitepackage.socialmedia:
    parent: rlt3sitepackage.footer
  rlt3sitepackage.subscriptions:
    label: 'Subscriptions'
    parent: rlt3sitepackage.socialmedia

settings:
  ### Navigation
  # Breadcrumb & choose theme
  breadcrumb.enable:
    label: 'Enable breadcrumb navigation'
    default: true
    type: bool
    category: rlt3sitepackage.navigation

  # Header Language Navigation
  header.languagenavigation.enable:
    label: 'Enable Header Language Navigation'
    category: rlt3sitepackage.navigation
    type: bool
    default: true

  header.languagenavigation.languageValue:
    label: 'Header Language Navigation Settings'
    description: 'Comma separated list of language uids or set to "auto" to load all enabled system languages'
    category: rlt3sitepackage.navigation
    type: string
    default: 'auto'


  # Footer Navigation
  footer.navigation.enable:
    label: 'Enable Footer Navigation'
    category: rlt3sitepackage.navigation
    type: bool
    default: true

  footer.navigation.menuRoot:
    label: 'Footer menu root uid'
    description: 'The subpages of this page are displayed in the footer'
    category: rlt3sitepackage.navigation
    type: int
    default: 6

  footer.navigation.includeNotInMenu:
    label: 'Include items not in menu'
    category: rlt3sitepackage.navigation
    type: bool
    default: false

  # Footer Language Navigation
  footer.languagenavigation.enable:
    label: 'Enable Footer Language Navigation'
    category: rlt3sitepackage.navigation
    type: bool
    default: true

  footer.languagenavigation.languageValue:
    label: ' Footer Language Navigation Settings'
    description: 'Comma separated list of language uids or set to "auto" to load all enabled system languages'
    category: rlt3sitepackage.navigation
    type: string
    default: 'auto'

  # Theme - Color Scheme
  theme.colorScheme:
    default: theme-caramel-cream
    type: string
    enum:
      - theme-caramel-cream
      - theme-ocean-breeze
      - theme-forest-mist
      - theme-violet-velvet
    category: rlt3sitepackage.style

  # Theme - Colors
  css.primary:
    default: '#b30027'
    type: string
    category: rlt3sitepackage.css-variables

  ### Header
  # Logo
  header.logo.enable:
    label: 'Enable a header Logo'
    description: 'It will appear in the header on top of the main page'
    category: rlt3sitepackage.header
    type: bool
    default: true

  header.logo.alt:
    label: 'Logo Alt text'
    category: rlt3sitepackage.header
    description: 'Alternative text of the logo for the visually impaired'
    type: string
    default: 'Logo'

  header.logo.width:
    label: 'Logo Width'
    category: rlt3sitepackage.header
    type: number
    default: 64

  header.logo.height:
    label: 'Logo Height'
    category: rlt3sitepackage.header
    type: string
    default: 'auto'

  # Solr Search Form
  solr.search.enable:
    label: 'Enable Search Form'
    category: rlt3sitepackage.header
    type: bool
    default: false

  plugin.tx_solr.search.targetPage:
    category: rlt3sitepackage.header
    label: 'Search Results Target Page'
    description: 'The uid number of the page, where the search results appear. Default is set to 0 (zero). Which means the results appear on the same page.'
    type: int
    default: 0

  plugin.solr.templateRootPath:
    category: rlt3sitepackage.header
    label: 'Apache Solr Template Roth Path'
    type: string
    default: 'EXT:rlt3sitepackage/Resources/Private/Extensions/Solr/Templates/'

  plugin.solr.partialRootPath:
    category: rlt3sitepackage.header
    label: 'Apache Solr Partial Roth Path'
    type: string
    default: 'EXT:rlt3sitepackage/Resources/Private/Extensions/Solr/Partials/'

  plugin.solr.layoutRootPath:
    category: rlt3sitepackage.header
    label: 'Apache Solr Layout Roth Path'
    type: string
    default: 'EXT:rlt3sitepackage/Resources/Private/Extensions/Solr/Layouts/'

  ### Footer settings
  # Copyright settings
  footer.copyright.enable:
    label: 'Enable Copyright'
    category: rlt3sitepackage.footer
    type: bool
    default: true

  # OpenStreetMap settings
  footer.openstreetmap.enable:
    label: 'Enable OpenStreetMap'
    category: rlt3sitepackage.footer
    type: bool
    default: true

  footer.openstreetmap.src:
    label: 'OpenStreetMap Source (URL)'
    category: rlt3sitepackage.footer
    description: 'Source URL of the OpenStreetMap'
    type: string
    default: 'https://www.openstreetmap.org/export/embed.html?bbox=7.369127869606019%2C46.55292129624824%2C7.372668385505676%2C46.554544443415516&amp;layer=mapnik&amp;marker=46.55373287590018%2C7.370898127555847'

  footer.openstreetmap.title:
    label: 'OpenStreetMap Title'
    category: rlt3sitepackage.footer
    type: string
    default: 'OpenStreetMap My Location'

  footer.openstreetmap.width:
    label: 'OpenStreetMap Width'
    category: rlt3sitepackage.footer
    type: number
    default: 250

  footer.openstreetmap.height:
    label: 'OpenStreetMap Height'
    category: rlt3sitepackage.footer
    type: number
    default: 206

  # Social Media settings
  footer.socialmedia.enable:
    label: 'Enable Social Media'
    category: rlt3sitepackage.footer
    type: bool
    default: true

  footer.socialmedia.subscriptions.github.label:
    label: 'GitHub Label'
    category: rlt3sitepackage.footer.socialmedia.subscriptions
    type: string
    default: 'GitHub'

  footer.socialmedia.channels.github.url:
    label: 'GitHub Url'
    description: 'Insert the full account url'
    category: rlt3sitepackage.footer.socialmedia.subscriptions
    type: string
    default: ''

  footer.socialmedia.channels.linkedin.label:
    label: 'LinkedIn Label'
    category: rlt3sitepackage.footer.socialmedia.subscriptions
    type: string
    default: 'LinkedIn'

  footer.socialmedia.channels.linkedin.url:
    label: 'LinkedIn Url'
    description: 'Insert the full account url'
    category: rlt3sitepackage.footer.socialmedia.subscriptions
    type: string
    default: ''

  ### Meta data settings
  # Favicon
  meta.favicon:
    label: 'Favicon'
    description: 'This icon is displayed in search engine results and in the browser tab'
    category: rlt3sitepackage.meta
    type: string
    default: 'EXT:rlt3sitepackage/Resources/Public/Icons/favicon.ico'

  meta.apple-mobile-web-app-capable:
    label: 'apple-mobile-web-app-capable'
    category: rlt3sitepackage.meta
    type: string
    default: 'no'

  meta.google-site-verification:
    label: 'google-site-verification'
    category: rlt3sitepackage.meta
    type: string
    default: ''

  ### Global configuration settings
  config.no_cache:
    label: 'No Cache'
    category: rlt3sitepackage.config
    type: bool
    default: false

  config.removeDefaultJS:
    label: 'Remove default JavaScript'
    category: rlt3sitepackage.config
    type: string
    enum:
      '0': 'Do not remove'
      '1': 'Remove'
      'external': 'Move to external file'
    default: '0'

  config.compressJs:
    label: 'Compress JavaScript'
    category: rlt3sitepackage.config
    type: bool
    default: true

  config.compressCss:
    label: 'Compress CSS'
    category: rlt3sitepackage.config
    type: bool
    default: true

  config.concatenateJs:
    label: 'Concatenate JavaScript'
    category: rlt3sitepackage.config
    type: bool
    default: true

  config.concatenateCss:
    label: 'Concatenate CSS'
    category: rlt3sitepackage.config
    type: bool
    default: true

  config.admPanel:
    label: 'Admin Panel'
    category: rlt3sitepackage.config
    type: bool
    default: true

  config.headerComment:
    label: 'Header Comment'
    category: rlt3sitepackage.config
    type: string
    default: 'Made from scratch according to the sophisticated TYPO3 documentations found on https://docs.typo3
    .org/m/typo3/tutorial-sitepackage/main/en-us/Index.html - '

  config.sendCacheHeaders:
    label: 'Send cache headers'
    description: 'Allow appropriate caching by transparent proxies and browser clients'
    category: rlt3sitepackage.config
    type: bool
    default: true

  page.templates.template_path:
    label: 'Page template path'
    category: rlt3sitepackage.templates
    description: 'Path to the templates of the ResterLand Site Package.'
    type: string
    enum:
      'EXT:rlt3sitepackage/Resources/Private/PageView/': 'default'
      'EXT:rlt3sitepackage/Resources/Private/Learning/': 'learning'
    default: 'EXT:rlt3sitepackage/Resources/Private/PageView/'

